
      - name: Verificar geracao do modelo .tflite
        run: 
          if [ ! -f model.tflite ]; then
            echo "Arquivo model.tflite nao encontrado."
            exit 1
          fi

      - name: Finalizacao
        run: echo "Desafio executado com sucesso!"